package com.legec.ceburilo.web.directions.model


object Language {
    val ARABIC = "ar"
    val BULGARIAN = "bg"
    val BENGALI = "bn"
    val CATALAN = "ca"
    val CZECH = "cs"
    val DANISH = "da"
    val GERMAN = "de"
    val GREEK = "el"
    val ENGLISH = "en"
    val ENGLISH_AUSTRALIAN = "en-AU"
    val ENGLISH_GREAT_BRITAIN = "en-GB"
    val SPANISH = "es"
    val BASQUE = "eu"
    val FARSI = "fa"
    val FINNISH = "fi"
    val FILIPINO = "fil"
    val FRENCH = "fr"
    val GALICIAN = "gl"
    val GUJARATI = "gu"
    val HINDI = "hi"
    val CROATIAN = "hr"
    val HUNGARIAN = "hu"
    val INDONESIAN = "id"
    val ITALIAN = "it"
    val HEBREW = "iw"
    val JAPANESE = "ja"
    val KANNADA = "kn"
    val KOREAN = "ko"
    val LITHUANIAN = "lt"
    val LATVIAN = "lv"
    val MALAYALAM = "ml"
    val MARATHI = "mr"
    val DUTCH = "nl"
    val NORWEGIAN = "no"
    val POLISH = "pl"
    val PORTUGUESE = "pt"
    val PORTUGUESE_BRAZIL = "pt-BR"
    val PORTUGUESE_PORTUGAL = "pt-PT"
    val ROMANIAN = "rp"
    val RUSSIAN = "ru"
    val SLOVAK = "sk"
    val SLOVENIAN = "sl"
    val SERBIAN = "sr"
    val SWEDISH = "sv"
    val TAMIL = "ta"
    val TELUGU = "te"
    val THAI = "th"
    val TAGALOG = "tl"
    val TURKISH = "tr"
    val UKRAINIAN = "uk"
    val VIETNAMESE = "vi"
    val CHINESE_SIMPLIFIED = "zh-CN"
    val CHINESE_TRADITIONAL = "zh-TW"
}